
spring.application.name=SC-Antworten-Generator-CLI

# Für Liste der Modelle und Preise siehe:
# https://ai.google.dev/gemini-api/docs/models?hl=de
# https://ai.google.dev/gemini-api/docs/pricing?hl=de
#
# "lite"-Modelle sind schneller und günstiger als die "Pro"-Modelle.
# Hier ist der technische Name eines Modells einzutragen, welches
# unter "Modellcode" auf der Detailseite eines Models zu finden
# ist, siehe z.B.:
# https://ai.google.dev/gemini-api/docs/models/gemini-3.1-flash-lite?hl=de
spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite

# Parameter zum Steuern der Kreativität für die KI-Antworten; je höher,
# desto kreativer, aber auch unvorhersehbarer werden die Antworten.
spring.ai.google.genai.chat.options.temperature=0.5


# API-Key in separate Datei "apikey.properties" ausgelagert,
# damit er nicht versehentlich in ein öffentliches Git-Repository
# gelangt. Nach Eintragen API-Key in diese Datei am besten
# mit dem folgenden Befehl Git anweisen, Änderungen in dieser
# Datei zu ignorieren:
# git update-index --skip-worktree src\main\resources\apikey.properties
spring.config.import=classpath:apikey.properties
