
spring.application.name=SC-Antworten-Generator-CLI

spring.config.import=classpath:api-key.properties

# https://ai.google.dev/gemini-api/docs/models?hl=de
spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite

spring.ai.google.genai.chat.options.temperature=0.5  

